<a href="https://colab.research.google.com/github/christinacheng-code/datasci_1_loading/blob/main/datasci_1_loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
brfss_df = pd.read_csv('/content/Behavioral_Risk_Factor_Surveillance_System_(BRFSS)_Historical_Questions_20260930.csv')

In [ ]:
brfss_df.head(10)

,Topic,Question,VariableName,Responses,Year,Type,DisplayOrder
0,Health Status,Would you say that in general your health is:,GENHLTH,1=Excellent 2=Very good 3=Good 4=Fair 5=Poor 7...,2023,Core Question,1
1,Healthy Days,"Now thinking about your physical health, which...",PHYSHLTH,1-30=Number of days 88=None 77=Don’t know/Not ...,2023,Core Question,2
2,Healthy Days,"Now thinking about your mental health, which i...",MENTHLTH,1-30=Number of days 88=None 77=Don’t know/Not ...,2023,Core Question,3
3,Healthy Days,"During the past 30 days, for about how many da...",POORHLTH,1-30=Number of days 88=None 77=Don’t know/Not ...,2023,Core Question,4
4,Health Care Access,What is the current source of your primary hea...,PRIMINS1,1=A plan purchased through an employer or unio...,2023,Core Question,5
5,Health Care Access,Do you have one person (or a group of doctors)...,PERSDOC3,"1=Yes, only one 2=More than one 3=No 7=Don’t k...",2023,Core Question,6
6,Health Care Access,Was there a time in the past 12 months when yo...,MEDCOST1,1=Yes 2=No 7=Don’t know/Not sure 9=Refused,2023,Core Question,7
7,Health Care Access,About how long has it been since you last visi...,CHECKUP1,1=Within past year (anytime less than 12 month...,2023,Core Question,8
8,Exercise (Physical Activity),"During the past month, other than your regular...",EXERANY2,1=Yes 2=No 7=Don’t know/Not Sure 9=Refused,2023,Core Question,9
9,Exercise (Physical Activity),What type of physical activity or exercise did...,EXRACT12,1=Walking 2=Running or jogging 3=Gardening or ...,2023,Core Question,10

In [4]:
import pandas as pd

In [5]:
heart_df = pd.read_csv('/content/heart.csv')

In [6]:
heart_df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [7]:
hiv_df = pd.read_excel('/content/cdc_256154_DS1.xlsx', sheet_name='Table 1a')

In [8]:
hiv_df.head(10)

,"Table 1a. HIV diagnoses, by year of diagnosis and selected characteristics, 2019–2023—United States",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,2019,NaN,2020 (COVID-19 pandemic)a,NaN,2021,NaN,2022,NaN,2023,NaN
1,NaN,No.,Rateb,No.,Rateb,No.,Rateb,No.,Rateb,No.,Rateb
2,Sex,,,,,,,,,,
3,Male,29518,18.3,25015,15.2,29273,17.8,30734,18.6,31500,19
4,Female,6890,4.1,5447,3.3,6543,3.9,6987,4.2,7350,4.3
5,Age at diagnosis (yr),,,,,,,,,,
6,< 13,59,0.1,59,0.1,53,0.1,61,0.1,57,0.1
7,13–14,22,0.3,15,0.2,15,0.2,21,0.2,22,0.3
8,15–19,1665,7.9,1291,6,1487,6.9,1369,6.3,1465,6.6
9,20–24,6006,27.7,4899,22.8,5569,25.9,5705,26.3,5630,25.8

In [9]:
hepatitis_b_df = pd.read_excel('/content/table-2.7.xlsx')

In [10]:
hepatitis_b_df.head(10)

,Unnamed: 0,"Table 2.7. Numbers and rates* of deaths with hepatitis B virus infection listed as a cause of death† among residents, by state or jurisdiction — United States, 2016–2020",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,State or Jurisdiction,2016,2016,2017,2017,2018,2018,2019,2019,2020,2020
1,NaN,NaN,No.,Rate*,No.,Rate*,No.,Rate*,No.,Rate*,No.,Rate*
2,NaN,Alabama,19,UR§,19,UR§,19,UR§,12,UR§,12,UR§
3,NaN,Alaska,S¶,UR§,S¶,UR§,S¶,UR§,S¶,UR§,S¶,UR§
4,NaN,Arizona,29,0.34,19,UR§,31,0.34,30,0.34,20,0.24
5,NaN,Arkansas,10,UR§,22,0.6,17,UR§,16,UR§,19,UR§
6,NaN,California,337,0.78,346,0.8,304,0.67,327,0.7,357,0.75
7,NaN,Colorado,23,0.39,32,0.51,26,0.39,35,0.49,34,0.5
8,NaN,Connecticut,S¶,UR§,S¶,UR§,13,UR§,S¶,UR§,S¶,UR§
9,NaN,Delaware,S¶,UR§,S¶,UR§,S¶,UR§,S¶,UR§,S¶,UR§

In [11]:
hepatitis_df = pd.read_excel('/content/table-5.3.xlsx')

In [12]:
hepatitis_df.head(10)

,Unnamed: 0,"Appendix Table 3. Numbers and rates* of reported acute hepatitis B infections† and acute hepatitis C infections† among adults aged 18-40 years old, by demographic characteristics — United States 2020",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,Characteristics,Acute Hepatitis B,NaN,Acute Hepatitis C,NaN
1,NaN,NaN,No.,Rate*,No.,Rate*
2,NaN,Total§,690,0.7,2908,2.9
3,NaN,Sex,,,,
4,NaN,Male,402,0.8,1824,3.6
5,NaN,Female,287,0.6,1079,2.2
6,NaN,Race/ethnicity,,,,
7,NaN,American Indian/Alaskan Native,4,0.4,40,5.1
8,NaN,Asian/Pacific Islander,16,0.2,29,0.4
9,NaN,"Black, non-Hispanic",102,0.7,202,1.4

In [14]:
import json

with open('/content/health_life_expectancy.json', 'r') as file:
    data = json.load(file)

life_expectancy_df = pd.json_normalize(
    data,
    record_path='values',
    meta=['country_code']
)

In [15]:
life_expectancy_df.head(10)

         country sex  value country_code
0          Spain   F   86.3           ES
1          Spain   M   80.7           ES
2         France   F   85.9           FR
3         France   M   79.7           FR
4    Switzerland   F   85.7           CH
5    Switzerland   M   81.9           CH
6          Italy   F   85.6           IT
7          Italy   M   81.2           IT
8  Liechtenstein   F   85.5           LI
9  Liechtenstein   M   80.7           LI

In [23]:
import json

with open('/content/WHO_LifeBirth.json', 'r', encoding='utf-8-sig') as file:
    data = json.load(file)

life_birth_df = pd.DataFrame(data['value'])

In [24]:
life_birth_df.head(10)

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,TimeDim,Dim1Type,Dim1,Dim2Type,Dim2,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,22847621,WHOSIS_000001,COUNTRY,CAN,YEAR,1920,SEX,BTSX,None,None,...,None,82.8,82.80972,None,None,WHO life table method: Vital registration,2020-06-04T11:21:09.77+02:00,1920,1920-01-01T00:00:00+01:00,1920-12-31T00:00:00+01:00
1,24614313,WHOSIS_000001,COUNTRY,AFG,YEAR,2000,SEX,MLE,None,None,...,None,54.6,54.57449,None,None,None,2020-12-04T16:59:42.513+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
2,24614317,WHOSIS_000001,COUNTRY,AFG,YEAR,2010,SEX,MLE,None,None,...,None,59.6,59.60036,None,None,None,2020-12-04T16:59:43.013+01:00,2010,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00
3,24614321,WHOSIS_000001,COUNTRY,AFG,YEAR,2015,SEX,MLE,None,None,...,None,61.0,61.03658,None,None,None,2020-12-04T16:59:43.423+01:00,2015,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
4,24614325,WHOSIS_000001,COUNTRY,AFG,YEAR,2019,SEX,MLE,None,None,...,None,63.3,63.28709,None,None,None,2020-12-04T16:59:43.533+01:00,2019,2019-01-01T00:00:00+01:00,2019-12-31T00:00:00+01:00
5,24614329,WHOSIS_000001,COUNTRY,AFG,YEAR,2000,SEX,FMLE,None,None,...,None,55.4,55.41726,None,None,None,2020-12-04T16:59:43.61+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
6,24614333,WHOSIS_000001,COUNTRY,AFG,YEAR,2010,SEX,FMLE,None,None,...,None,60.3,60.29720,None,None,None,2020-12-04T16:59:43.72+01:00,2010,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00
7,24614337,WHOSIS_000001,COUNTRY,AFG,YEAR,2015,SEX,FMLE,None,None,...,None,62.3,62.34584,None,None,None,2020-12-04T16:59:43.847+01:00,2015,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
8,24614341,WHOSIS_000001,COUNTRY,AFG,YEAR,2019,SEX,FMLE,None,None,...,None,63.2,63.15551,None,None,None,2020-12-04T16:59:43.927+01:00,2019,2019-01-01T00:00:00+01:00,2019-12-31T00:00:00+01:00
9,24614345,WHOSIS_000001,COUNTRY,AFG,YEAR,2000,SEX,BTSX,None,None,...,None,55.0,54.98949,None,None,None,2020-12-04T16:59:44.053+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00

In [25]:
import json

with open('/content/WHO_Life60.json', 'r', encoding='utf-8-sig') as file:
    data = json.load(file)

life_60_df = pd.DataFrame(data['value'])

In [26]:
life_60_df.head(10)

,Id,IndicatorCode,SpatialDimType,SpatialDim,TimeDimType,TimeDim,Dim1Type,Dim1,Dim2Type,Dim2,...,DataSourceDim,Value,NumericValue,Low,High,Comments,Date,TimeDimensionValue,TimeDimensionBegin,TimeDimensionEnd
0,24614315,WHOSIS_000015,COUNTRY,AFG,YEAR,2000,SEX,MLE,None,None,...,None,13.6,13.63259,None,None,None,2020-12-04T16:59:42.623+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
1,24614319,WHOSIS_000015,COUNTRY,AFG,YEAR,2010,SEX,MLE,None,None,...,None,15.1,15.07067,None,None,None,2020-12-04T16:59:43.377+01:00,2010,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00
2,24614323,WHOSIS_000015,COUNTRY,AFG,YEAR,2015,SEX,MLE,None,None,...,None,15.7,15.67539,None,None,None,2020-12-04T16:59:43.47+01:00,2015,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
3,24614327,WHOSIS_000015,COUNTRY,AFG,YEAR,2019,SEX,MLE,None,None,...,None,15.4,15.39356,None,None,None,2020-12-04T16:59:43.58+01:00,2019,2019-01-01T00:00:00+01:00,2019-12-31T00:00:00+01:00
4,24614331,WHOSIS_000015,COUNTRY,AFG,YEAR,2000,SEX,FMLE,None,None,...,None,14.2,14.20647,None,None,None,2020-12-04T16:59:43.673+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
5,24614335,WHOSIS_000015,COUNTRY,AFG,YEAR,2010,SEX,FMLE,None,None,...,None,15.2,15.16855,None,None,None,2020-12-04T16:59:43.77+01:00,2010,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00
6,24614339,WHOSIS_000015,COUNTRY,AFG,YEAR,2015,SEX,FMLE,None,None,...,None,15.5,15.51821,None,None,None,2020-12-04T16:59:43.893+01:00,2015,2015-01-01T00:00:00+01:00,2015-12-31T00:00:00+01:00
7,24614343,WHOSIS_000015,COUNTRY,AFG,YEAR,2019,SEX,FMLE,None,None,...,None,15.1,15.05771,None,None,None,2020-12-04T16:59:43.973+01:00,2019,2019-01-01T00:00:00+01:00,2019-12-31T00:00:00+01:00
8,24614347,WHOSIS_000015,COUNTRY,AFG,YEAR,2000,SEX,BTSX,None,None,...,None,13.9,13.92182,None,None,None,2020-12-04T16:59:44.113+01:00,2000,2000-01-01T00:00:00+01:00,2000-12-31T00:00:00+01:00
9,24614351,WHOSIS_000015,COUNTRY,AFG,YEAR,2010,SEX,BTSX,None,None,...,None,15.1,15.12046,None,None,None,2020-12-04T16:59:44.23+01:00,2010,2010-01-01T00:00:00+01:00,2010-12-31T00:00:00+01:00

CSV#1
Topic: Health topic of the survey
question: question asked
variablename: variable name used to identify the question
responses: response to question
year: date
type: type of question
displayorder: order in which question is displayed

CSV#2
age: patient age
sex: patient sex (0 or 1)
cp: type of chest pain
trestbps: resting blood pressure
chol: cholesterol
fbs: whether fasting blood sugar is above 120mg/dL
restecg: ECG results
thalach: max health rate
exang: chesting pain during exercise
oldpeak: depression
slope: slope of ST during exercise
ca: # of major blood vessels
thal: results from heart test
target: presence of heart disease

json#1
country: country name
sex: sex
value: life expectancy in years
country code: country identification